hub:
    extraConfig:
     myConfig: |
      tornado_settings_values = {
        "websocket_max_message_size": 104857600
        }
      c.KubeSpawner.args = [
        f'--NotebookApp.tornado_settings={tornado_settings_values}'
        ]